name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out this repo
      - uses: actions/checkout@v3

      # 2) Set up Node
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3) Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4) Build (Webpack compiles TypeScript -> dist/bundle.js)
      - name: Build
        run: npm run build

      # 5) Copy index.html and tasks.json into dist/ 
      #    so they are deployed to GitHub Pages along with bundle.js
      - name: Copy additional files
        run: |
          cp index.html dist/index.html
          cp tasks.json dist/tasks.json

      # 6) Deploy the /dist folder to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
